apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-2y0g
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0074-tenant/tkrw-pr712-0075-0074-app/devfile-sample-2y0g@sha256:0ddef3a825c6a37b9c65e1ce9ead239e5013f62d244fbcf835b5e3f289358bf5
        name: my-nodejs
        resources: {}
status: {}
